### ISSUE TITLE
Provider Roadmap and clarity on AS3 resources.

### ISSUE THREAD

**Issue by stobias123** [terraform-providers/terraform-provider-bigip#190]
Just want to provide some additional comments and centralize discussion regarding as3 resources as mentioned in #89

I think the community needs to understand the intended implementation of as3 resources and how this will impact the provider and management of f5 through terraform in general.

/cc @dannyk81

**Comment by stobias123** [comment]
To add some color around my use case...

I've now implemented a workflow based primarily in terraform to manage F5 in our environment.

This relies heavily on the ability to interact with HCL across multiple providers and other infrastructure components.

I have to echo some of the points @dannyk81 is making in #89... While as3 might be a step in the right direction towards declarative config, it should not be considered a replacement for terraform. Another DSL doesn't provide the value we see from terraform, and ultimately would reduce the interoperability of the provider with other bits of infrastructure.


...AWS has CloudFormation but sill supports terraform as a first class citizen through direct api access to each object you might want to interact with :)

**Comment by papineni87** [comment]
AS3 is not a replacement for terraform, only the thing is we will develop terraform resources for as3 schema ( indeed it will take time ) , which will cover most of the bigip functionality objects as far as AS3 is supporting.  Until then we will still support/develop individual resources as it is happening now. 

Since AS3 is declarative model and is covering all bigip functionality objects, and is evolving to cover new bigip releases/features, if we are able to develop atleast one terraform resource for as3 schema object then we can apply for the entire schema.

Scottdware/go-bigip has picked up activity in recent months after being idle. But f5devcentral/go-bigip and scottdware/go-bigip  has diverged a lot. It is bit difficult to rebase our vendor repo to scottdware/go-bigip, instead we can take recent commits from that repo to f5decentral/go-bigip repo. we can start doing releases in go-bigip also and now we have the option of raising issues in f5devcentral/go-bigip.

**Comment by focrensh** [comment]
Closing based on the response above. If a feature is available through AS3, it should be performed using that resource.

**Comment by stobias123** [comment]
@focrensh  - so to close the loop here, resources will be supported via AS3 config, (JSON) but not natively through terraform?

**Comment by focrensh** [comment]
This is the direction for F5 integrations across all ecosystems and platforms. It provides a familiar user experience when switching between tooling/automation. The idea is that while you may need to learn AS3 objects/schema, you will not need to then learn or have BIG-IP DSK around object mapping (knowing each resource). As an example, you will not need to manage parent/child relationships, object re-use, idempotency, atomicity, etc (i realize Terraform does handle some of that natively). I would be happy to chat more about this on a call as well if you're interested.

**Comment by stobias123** [comment]
Sure, happy to discuss on a call, I have many clients on F5 and this direction seems like a step in the right direction but it's rather unfortunate. Using just another JSON doc lacks type safety, dependency mapping, text editor support, and just about everything else that was good in the ecosystem.

 If my you guys are open to community feedback I'm happy to provide some :)
